[main]
application_command = 'bash /home/ubuntu/algorithm.sh'
local_input_files = [
    {'dir' = '/home/ubuntu/input_files', 'name' = 'data.txt'}
]
local_result_files = [
    {'dir' = '/home/ubuntu/result_files', 'name' = 'data.txt'},
    {'dir' = '/home/ubuntu/result_files', 'name' = 'parameters.txt'}
]
parameters_as_json = false
